In [1]:
import numpy as np

In [2]:
np.random.randint(18,20,200)

array([18, 18, 19, 18, 19, 19, 19, 19, 18, 18, 18, 18, 19, 18, 19, 18, 19,
       19, 19, 19, 19, 19, 19, 18, 18, 18, 19, 19, 18, 19, 18, 19, 18, 19,
       19, 18, 19, 19, 19, 19, 18, 18, 18, 18, 18, 18, 19, 18, 19, 18, 18,
       18, 19, 19, 18, 19, 19, 19, 18, 18, 19, 19, 19, 19, 18, 19, 18, 18,
       19, 18, 18, 19, 19, 19, 19, 18, 18, 19, 19, 19, 19, 19, 18, 19, 19,
       19, 18, 19, 19, 18, 18, 18, 18, 18, 19, 19, 19, 19, 19, 19, 18, 18,
       18, 19, 18, 19, 18, 18, 19, 18, 19, 18, 18, 19, 18, 18, 19, 19, 19,
       19, 19, 18, 18, 18, 18, 19, 19, 19, 19, 18, 18, 18, 19, 19, 19, 18,
       19, 19, 18, 18, 19, 19, 19, 19, 19, 18, 18, 19, 19, 18, 18, 18, 18,
       19, 19, 18, 19, 18, 19, 19, 18, 19, 19, 19, 18, 19, 18, 19, 18, 19,
       19, 19, 19, 18, 19, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 19, 18,
       19, 19, 19, 18, 19, 18, 18, 18, 19, 18, 18, 19, 18])

In [3]:
np.random.normal(18,21,200)

array([-15.49751798,  41.45103618,  -8.34450915,  -8.41346487,
        38.14208747,  -7.98864736,  28.37243246,  14.1304576 ,
        39.07576932,  27.27735394,   0.42464467,  27.42477224,
        21.84804375,  23.31113921,  27.27780142,  21.29756757,
        34.43580789, -17.80448106,  25.65811061,  28.50382775,
        12.8060809 ,  13.5386463 , -12.79959452,  15.30066131,
        35.81029154,  -1.92629565,  -5.90180883,  12.44322421,
         2.84560895,  43.12991393,  13.47156269,  -5.21184463,
        12.84850211,  56.99829091,  12.13210139,   5.07990996,
       -10.61838892,  11.60710246,  30.17572559, -10.39217618,
        11.10483415,  19.80085089,  26.31955323,  16.2895219 ,
       -11.86154925,  52.68814227,   6.71440839,  22.27557382,
         8.74631069,  29.24590694,  34.54005452,  36.15437961,
        30.47545145,  26.5903675 ,  60.64879869,  30.99015554,
        50.85871329,  28.35246791,  36.59547478,  15.79490783,
        16.88338805,  -2.11721903,  31.45639075,  49.85

In [4]:
h=[38,20,5,8,9]
h

[38, 20, 5, 8, 9]

In [5]:
d=[]
for i in h:
    d.append(i+5)
d

[43, 25, 10, 13, 14]

In [6]:
s=(6,2,3,9,7,5,8)
s

(6, 2, 3, 9, 7, 5, 8)

In [7]:
tuple(x**2 for x in s)

(36, 4, 9, 81, 49, 25, 64)

In [10]:
y = list(s)
k = []
for i in y:
  k.append(i**2)
s=tuple(k)
s


(1679616, 256, 6561, 43046721, 5764801, 390625, 16777216)

In [12]:
m=[]
for i in s:
  if i>30:
    m.append(i)


In [13]:
m

[1679616, 256, 6561, 43046721, 5764801, 390625, 16777216]

In [14]:
arr=np.array([20,50,30,70,80,40,36,23,98])

In [15]:
arr

array([20, 50, 30, 70, 80, 40, 36, 23, 98])

In [16]:
arr**2

array([ 400, 2500,  900, 4900, 6400, 1600, 1296,  529, 9604])